# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 141bc4be6724f01ffaefd41236a37dc24bd55e2733be8b01c93b9256af8647c6d321a046e5be04bff8f9752160de1d46bf6486f79c01637565fa6fb12e25a46b

test:
  secret_key_base: 79b6359d8681edc590b8db9aae1dd9e1724ac15f62d3ac34f340e1a276b331fba5bb8f8f656022bf2c9d07b437f514c048a13dcd5b7dfaf3046067e71c26d5fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
