#!/usr/bin/perl

my %last_name = qw{
  fred flintstone Wilma Flintstone Barney Rubble
  betty rubble Bamm-Bamm Rubble PEBBLES FLINTSTONE
};

my @result = sort {
  "\L$last_name{$a}" cmp "\L$last_name{$b}"
    or
  "\L$a" cmp "\L$b"
} keys %last_name;

foreach (@result) {
  print "$_ $last_name{$_}\n";
}
