#!/usr/bin/perl
print "Enter a String: ";
chomp (my $string = <STDIN>);
print "Enter a substring: ";
chomp (my $substring = <STDIN>);


my $index = -1;

while (1) {
  $index = index($string, $substring, $index + 1);
  if ($index == -1) {
    last;
  } else {
    print "$index\n";
  }
}
