#!/usr/bin/perl

use 5.014;
sub divisors {
  my $number = shift;

  my @divisors = ();
  foreach my $divisor (2 .. ($number/2)) {
    push @divisors, $divisor unless $number % $divisor;
  }

  return @divisors;
}
print "Enter a num: ";
chomp (my $num = <STDIN>);
given ($num) {
  when (! /\A\d+\Z/) { say "Not a number!"}

  my @divisors = divisors($_);
  my @empty;
  when (@divisors ~~ @empty) { say "$_ is a prime"}
  default { say "$_ is divisible by @divisors"}
}
