#!/usr/bin/perl

use 5.014;

print "Enter a number: ";
chomp (my $num = <STDIN>);

given ($num) {
  when ($_ % 3 == 0) { say "Fizz"; continue}
  when ($_ % 5 == 0) { say "Bin"; continue}
  when ($_ % 7 == 0) { say "Sausage"; }
}
