#!/usr/bin/perl
use 5.014;

for (@ARGV) {
  say "\nProcessing $_";

  when (! -e) { say " File does not exist."}
  when (-r _) { say " Readable."; continue}
  when (-w _) { say " Writable."; continue}
  when (-x _) { say " Executable."}
}

