#!/usr/bin/perl

foreach (<*>) {
  my ($time_acess, $time_modify) = map {
    my($year, $month, $day) = (localtime($_))[5,4,3];
    $year += 1990;
    $month += 1;
    sprintf "%4d-%02d-%02d", $year, $month, $day;
  }(stat)[8,9];

  printf "%-10s %10s %10s\n", $_, $time_acess, $time_modify;
}
