#!/usr/bin/perl
## Copyright (C) 2013 by Ma
print "Please Enter a number: ";
chomp($a = <STDIN>);
print "Please Enter another: ";
chomp($b = <STDIN>);
$result = $a * $b;
print "$a multiplys $b equals $ result.\n"
