#! /usr/bin/perl
## Copyright (C) 2013 by Ma

$pi = 3.141592654;
print "What is the radius? ";
chomp($radius = <STDIN>);
if ($radius < 0) {
  $radius = 0;
}
print "The circumference of a circle with a radius of 12.5 is ". 2 * $pi * $radius ."\n";
