#!/usr/bin/perl
## Copyright (C) 2013 by Ma
sub average {
  my $sum = 0;
  foreach (@_) {
    $sum += $_;
  }
  $sum / @_;
}

sub above_average {
  my $average = average(@_);
  my @result;
  foreach (@_) {
    if ($_ > $average) {
      push @result, $_;
    }
  }
  @result;
}

my @fred = above_average(1..10);
print "\@fred if @fred\n";
print "(Should be 6 7 8 9 10)\n";
my @barney = above_average(100, 1..10);
print "\@barney is @barney\n";
print "(Should be just 100)\n";
