#!/usr/bin/perl
## Copyright (C) 2013 by Ma
print "What column width do you want: ";
chomp(my $width = <STDIN>);

print "Please enter some strings, end with Ctrl+D:\n";
chomp(my @strings = <STDIN>);

print "1234567890" x ($width/9 + 2), "\n";
printf "%${width}s\n" x @strings, @strings;
