#!/usr/bin/perl
## Copyright (C) 2013 by Ma
my $max = 0;
while (($key, $value) = each %ENV) {
  my $length = length($key);
  if ($length > $max) {
    $max = $length;
  }
}

while (($key, $value) = each %ENV) {
  printf "%-${max}s  %s\n", $key, $value;
}
