#!/usr/bin/perl
## Copyright (C) 2013 by Ma
print "Please enter some words, end with Ctrl+D.\n";
chomp(my @words = <STDIN>);

my %count;
foreach (@words) {
  $count{$_} += 1;
}

foreach my $word (sort keys %count) {
  print "$word was seen $count{$word} times.\n";
}
