#!/usr/bin/perl
## Copyright (C) 2013 by Ma
my %names = (
  fred => 'flintstone',
  barney => 'rubble',
  wilma => 'fintstione'
);
print "Please enter a first name: ";
chomp(my $name = <STDIN>);
print "${name}'s last name is $names{$name}.\n";
