#!/usr/bin/perl
## Copyright (C) 2013 by Ma
use 5.010;

while (<>) {                   # take one input line at a time
  chomp;
  if (/(?<word>\b\w*a\b)(?<rest>[\s\S]{0,5})/) {
    print "'word' contains '$+{word}'. The 'rest' is '$+{rest}'.\n";  # the special match vars
  } else {
    print "No match: |$_|\n";
  }
}
